<?php
/**
 * IngestApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Beater\Client\Test\Api;

use \Beater\Client\Configuration;
use \Beater\Client\ApiException;
use \Beater\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IngestApiTest Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IngestApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for drainTraceIngested
     *
     * .
     *
     */
    public function testDrainTraceIngested()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for drainTraceWrites
     *
     * .
     *
     */
    public function testDrainTraceWrites()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getIngestQueueStatus
     *
     * .
     *
     */
    public function testGetIngestQueueStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for importSource
     *
     * .
     *
     */
    public function testImportSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ingestNative
     *
     * .
     *
     */
    public function testIngestNative()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ingestOtlp
     *
     * .
     *
     */
    public function testIngestOtlp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reconcileTrace
     *
     * .
     *
     */
    public function testReconcileTrace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replayDeadLetter
     *
     * .
     *
     */
    public function testReplayDeadLetter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
