<?php
/**
 * ReviewsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Beater\Client\Test\Api;

use \Beater\Client\Configuration;
use \Beater\Client\ApiException;
use \Beater\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReviewsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReviewsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createReviewQueue
     *
     * .
     *
     */
    public function testCreateReviewQueue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enqueueReviewTaskFromTrace
     *
     * .
     *
     */
    public function testEnqueueReviewTaskFromTrace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listReviewTasks
     *
     * .
     *
     */
    public function testListReviewTasks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for promoteReviewAnnotation
     *
     * .
     *
     */
    public function testPromoteReviewAnnotation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for submitReviewAnnotation
     *
     * .
     *
     */
    public function testSubmitReviewAnnotation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
