<?php
/**
 * DatasetEvalReportTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Beater\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DatasetEvalReportTest Class Doc Comment
 *
 * @category    Class
 * @description DatasetEvalReport
 * @package     Beater\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DatasetEvalReportTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DatasetEvalReport"
     */
    public function testDatasetEvalReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aggregate_score"
     */
    public function testPropertyAggregateScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dataset_id"
     */
    public function testPropertyDatasetId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dataset_version_id"
     */
    public function testPropertyDatasetVersionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "evaluator_version_id"
     */
    public function testPropertyEvaluatorVersionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "report_id"
     */
    public function testPropertyReportId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "result_count"
     */
    public function testPropertyResultCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "results"
     */
    public function testPropertyResults()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
