<?php
/**
 * DatasetCaseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Beater\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DatasetCaseTest Class Doc Comment
 *
 * @category    Class
 * @description DatasetCase
 * @package     Beater\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DatasetCaseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DatasetCase"
     */
    public function testDatasetCase()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "case_id"
     */
    public function testPropertyCaseId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dataset_id"
     */
    public function testPropertyDatasetId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "input"
     */
    public function testPropertyInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "input_artifact_hashes"
     */
    public function testPropertyInputArtifactHashes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "normalizer_version"
     */
    public function testPropertyNormalizerVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "output"
     */
    public function testPropertyOutput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_environment_id"
     */
    public function testPropertySourceEnvironmentId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_span_id"
     */
    public function testPropertySourceSpanId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_trace_id"
     */
    public function testPropertySourceTraceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trace"
     */
    public function testPropertyTrace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trace_schema_version"
     */
    public function testPropertyTraceSchemaVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
