<?php
/**
 * ErrorResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Beater\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ErrorResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Error envelope returned by every fallible endpoint.
 * @package     Beater\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ErrorResponse"
     */
    public function testErrorResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
