# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.models.rollup_estimate import RollupEstimate

class TestRollupEstimate(unittest.TestCase):
    """RollupEstimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RollupEstimate:
        """Test RollupEstimate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RollupEstimate`
        """
        model = RollupEstimate()
        if include_optional:
            return RollupEstimate(
                value = 1.337,
                weighting = 'horvitz_thompson'
            )
        else:
            return RollupEstimate(
                value = 1.337,
                weighting = 'horvitz_thompson',
        )
        """

    def testRollupEstimate(self):
        """Test RollupEstimate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
