# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from beater_client.models.rollup_weighting import RollupWeighting

class TestRollupWeighting(unittest.TestCase):
    """RollupWeighting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRollupWeighting(self):
        """Test RollupWeighting"""
        # inst = RollupWeighting()

if __name__ == '__main__':
    unittest.main()
