/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The policy-π (§6.1) lever a [`CandidateChange`] targets, mirroring the planned
 * §21.1 `ChangeKind` taxonomy. Kept internal to this crate; intentionally not a
 * `/v1` contract type.
 * @export
 */
export const ChangeKind = {
    SystemPrompt: 'system_prompt',
    CustomerPrompt: 'customer_prompt',
    Code: 'code',
    ToolAdd: 'tool_add',
    ToolRemove: 'tool_remove',
    MemoryConfig: 'memory_config',
    ModelParams: 'model_params',
    DataLabel: 'data_label'
} as const;
export type ChangeKind = typeof ChangeKind[keyof typeof ChangeKind];


export function instanceOfChangeKind(value: any): boolean {
    for (const key in ChangeKind) {
        if (Object.prototype.hasOwnProperty.call(ChangeKind, key)) {
            if (ChangeKind[key as keyof typeof ChangeKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChangeKindFromJSON(json: any): ChangeKind {
    return ChangeKindFromJSONTyped(json, false);
}

export function ChangeKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeKind {
    return json as ChangeKind;
}

export function ChangeKindToJSON(value?: ChangeKind | null): any {
    return value as any;
}

export function ChangeKindToJSONTyped(value: any, ignoreDiscriminator: boolean): ChangeKind {
    return value as ChangeKind;
}

