/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pluggable optimizer strategies for the recursive self-improvement loop.
 * 
 * Each variant names a concrete prompt/agent optimizer family called for by
 * ARCHITECTURE §20.10 #7.6 ("named prompt/agent optimizer strategies, gated by
 * held-out statistics") and REQUIREMENTS R18.6. The names mirror the
 * reflective-proposal direction of §21.3 and the deferred population search of
 * §21.6c.
 * 
 * **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy
 * only *proposes* [`CandidateChange`]s; it never *accepts* one. Every candidate
 * from every strategy MUST flow through the existing held-out **Test** gate plus
 * the `beater-stats` confidence interval already implemented here
 * (`run_deterministic_experiment` / `run_judge_experiment` / `run_agent_experiment`
 * → [`compare_paired_scores`] → [`GateDecision`], §21.3) and the planned §21.4
 * anti-overfitting guardrail before it can be accepted. Proposal is not
 * acceptance: the strategy emits candidates, the gate decides.
 * @export
 */
export const OptimizerStrategy = {
    LlmRewrite: 'llm_rewrite',
    FewShotBayesian: 'few_shot_bayesian',
    Mipro: 'mipro',
    Evolutionary: 'evolutionary',
    Gepa: 'gepa',
    ParamSearch: 'param_search'
} as const;
export type OptimizerStrategy = typeof OptimizerStrategy[keyof typeof OptimizerStrategy];


export function instanceOfOptimizerStrategy(value: any): boolean {
    for (const key in OptimizerStrategy) {
        if (Object.prototype.hasOwnProperty.call(OptimizerStrategy, key)) {
            if (OptimizerStrategy[key as keyof typeof OptimizerStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OptimizerStrategyFromJSON(json: any): OptimizerStrategy {
    return OptimizerStrategyFromJSONTyped(json, false);
}

export function OptimizerStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizerStrategy {
    return json as OptimizerStrategy;
}

export function OptimizerStrategyToJSON(value?: OptimizerStrategy | null): any {
    return value as any;
}

export function OptimizerStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): OptimizerStrategy {
    return value as OptimizerStrategy;
}

