/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whether a roll-up estimate honestly accounts for tail-sampling bias (§1 #9,
 * #146). A tail-sampled population is deliberately non-representative, so an
 * unweighted mean is a biased estimator of the population it was drawn from.
 * @export
 */
export const RollupWeighting = {
    HorvitzThompson: 'horvitz_thompson',
    BiasedUnweighted: 'biased_unweighted'
} as const;
export type RollupWeighting = typeof RollupWeighting[keyof typeof RollupWeighting];


export function instanceOfRollupWeighting(value: any): boolean {
    for (const key in RollupWeighting) {
        if (Object.prototype.hasOwnProperty.call(RollupWeighting, key)) {
            if (RollupWeighting[key as keyof typeof RollupWeighting] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RollupWeightingFromJSON(json: any): RollupWeighting {
    return RollupWeightingFromJSONTyped(json, false);
}

export function RollupWeightingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollupWeighting {
    return json as RollupWeighting;
}

export function RollupWeightingToJSON(value?: RollupWeighting | null): any {
    return value as any;
}

export function RollupWeightingToJSONTyped(value: any, ignoreDiscriminator: boolean): RollupWeighting {
    return value as RollupWeighting;
}

