/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RollupWeighting } from './RollupWeighting';
import {
    RollupWeightingFromJSON,
    RollupWeightingFromJSONTyped,
    RollupWeightingToJSON,
    RollupWeightingToJSONTyped,
} from './RollupWeighting';

/**
 * A population-mean roll-up paired with the honesty label saying whether it is
 * inverse-probability weighted or a biased unweighted average (§1 #9). The label
 * travels with the value so a caller can never silently render a tail-sampled
 * average as if it were unbiased.
 * @export
 * @interface RollupEstimate
 */
export interface RollupEstimate {
    /**
     * 
     * @type {number}
     * @memberof RollupEstimate
     */
    value: number;
    /**
     * 
     * @type {RollupWeighting}
     * @memberof RollupEstimate
     */
    weighting: RollupWeighting;
}



/**
 * Check if a given object implements the RollupEstimate interface.
 */
export function instanceOfRollupEstimate(value: object): value is RollupEstimate {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('weighting' in value) || value['weighting'] === undefined) return false;
    return true;
}

export function RollupEstimateFromJSON(json: any): RollupEstimate {
    return RollupEstimateFromJSONTyped(json, false);
}

export function RollupEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollupEstimate {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'weighting': RollupWeightingFromJSON(json['weighting']),
    };
}

export function RollupEstimateToJSON(json: any): RollupEstimate {
    return RollupEstimateToJSONTyped(json, false);
}

export function RollupEstimateToJSONTyped(value?: RollupEstimate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'weighting': RollupWeightingToJSON(value['weighting']),
    };
}

