/* tslint:disable */
/* eslint-disable */
/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which split of the optimization substrate a [`CaseScore`] belongs to.
 * 
 * The RSI optimizer searches candidates against `Train`/`Val` and decides
 * acceptance only on the held-out `Test` split (§21.4). The split assignment is
 * the *caller's* responsibility — it owns the dataset and its train/val/test
 * partition — so [`run_optimization_round`] never reshuffles or peeks at the
 * split substrate; it merely routes each [`CaseScore`] to the gate by its tag.
 * @export
 */
export const Split = {
    Train: 'train',
    Val: 'val',
    Test: 'test'
} as const;
export type Split = typeof Split[keyof typeof Split];


export function instanceOfSplit(value: any): boolean {
    for (const key in Split) {
        if (Object.prototype.hasOwnProperty.call(Split, key)) {
            if (Split[key as keyof typeof Split] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SplitFromJSON(json: any): Split {
    return SplitFromJSONTyped(json, false);
}

export function SplitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Split {
    return json as Split;
}

export function SplitToJSON(value?: Split | null): any {
    return value as any;
}

export function SplitToJSONTyped(value: any, ignoreDiscriminator: boolean): Split {
    return value as Split;
}

