/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"fmt"
)

// ChangeKind The policy-π (§6.1) lever a [`CandidateChange`] targets, mirroring the planned §21.1 `ChangeKind` taxonomy. Kept internal to this crate; intentionally not a `/v1` contract type.
type ChangeKind string

// List of ChangeKind
const (
	CHANGEKIND_SYSTEM_PROMPT ChangeKind = "system_prompt"
	CHANGEKIND_CUSTOMER_PROMPT ChangeKind = "customer_prompt"
	CHANGEKIND_CODE ChangeKind = "code"
	CHANGEKIND_TOOL_ADD ChangeKind = "tool_add"
	CHANGEKIND_TOOL_REMOVE ChangeKind = "tool_remove"
	CHANGEKIND_MEMORY_CONFIG ChangeKind = "memory_config"
	CHANGEKIND_MODEL_PARAMS ChangeKind = "model_params"
	CHANGEKIND_DATA_LABEL ChangeKind = "data_label"
)

// All allowed values of ChangeKind enum
var AllowedChangeKindEnumValues = []ChangeKind{
	"system_prompt",
	"customer_prompt",
	"code",
	"tool_add",
	"tool_remove",
	"memory_config",
	"model_params",
	"data_label",
}

func (v *ChangeKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ChangeKind(value)
	for _, existing := range AllowedChangeKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ChangeKind", value)
}

// NewChangeKindFromValue returns a pointer to a valid ChangeKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChangeKindFromValue(v string) (*ChangeKind, error) {
	ev := ChangeKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ChangeKind: valid values are %v", v, AllowedChangeKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ChangeKind) IsValid() bool {
	for _, existing := range AllowedChangeKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ChangeKind value
func (v ChangeKind) Ptr() *ChangeKind {
	return &v
}

type NullableChangeKind struct {
	value *ChangeKind
	isSet bool
}

func (v NullableChangeKind) Get() *ChangeKind {
	return v.value
}

func (v *NullableChangeKind) Set(val *ChangeKind) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeKind) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeKind(val *ChangeKind) *NullableChangeKind {
	return &NullableChangeKind{value: val, isSet: true}
}

func (v NullableChangeKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

