/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RollupEstimate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RollupEstimate{}

// RollupEstimate A population-mean roll-up paired with the honesty label saying whether it is inverse-probability weighted or a biased unweighted average (§1 #9). The label travels with the value so a caller can never silently render a tail-sampled average as if it were unbiased.
type RollupEstimate struct {
	Value float64 `json:"value"`
	Weighting RollupWeighting `json:"weighting"`
}

type _RollupEstimate RollupEstimate

// NewRollupEstimate instantiates a new RollupEstimate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollupEstimate(value float64, weighting RollupWeighting) *RollupEstimate {
	this := RollupEstimate{}
	this.Value = value
	this.Weighting = weighting
	return &this
}

// NewRollupEstimateWithDefaults instantiates a new RollupEstimate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollupEstimateWithDefaults() *RollupEstimate {
	this := RollupEstimate{}
	return &this
}

// GetValue returns the Value field value
func (o *RollupEstimate) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RollupEstimate) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RollupEstimate) SetValue(v float64) {
	o.Value = v
}

// GetWeighting returns the Weighting field value
func (o *RollupEstimate) GetWeighting() RollupWeighting {
	if o == nil {
		var ret RollupWeighting
		return ret
	}

	return o.Weighting
}

// GetWeightingOk returns a tuple with the Weighting field value
// and a boolean to check if the value has been set.
func (o *RollupEstimate) GetWeightingOk() (*RollupWeighting, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weighting, true
}

// SetWeighting sets field value
func (o *RollupEstimate) SetWeighting(v RollupWeighting) {
	o.Weighting = v
}

func (o RollupEstimate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RollupEstimate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["weighting"] = o.Weighting
	return toSerialize, nil
}

func (o *RollupEstimate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"weighting",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRollupEstimate := _RollupEstimate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRollupEstimate)

	if err != nil {
		return err
	}

	*o = RollupEstimate(varRollupEstimate)

	return err
}

type NullableRollupEstimate struct {
	value *RollupEstimate
	isSet bool
}

func (v NullableRollupEstimate) Get() *RollupEstimate {
	return v.value
}

func (v *NullableRollupEstimate) Set(val *RollupEstimate) {
	v.value = val
	v.isSet = true
}

func (v NullableRollupEstimate) IsSet() bool {
	return v.isSet
}

func (v *NullableRollupEstimate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollupEstimate(val *RollupEstimate) *NullableRollupEstimate {
	return &NullableRollupEstimate{value: val, isSet: true}
}

func (v NullableRollupEstimate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollupEstimate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


