/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"fmt"
)

// Split Which split of the optimization substrate a [`CaseScore`] belongs to.  The RSI optimizer searches candidates against `Train`/`Val` and decides acceptance only on the held-out `Test` split (§21.4). The split assignment is the *caller's* responsibility — it owns the dataset and its train/val/test partition — so [`run_optimization_round`] never reshuffles or peeks at the split substrate; it merely routes each [`CaseScore`] to the gate by its tag.
type Split string

// List of Split
const (
	SPLIT_TRAIN Split = "train"
	SPLIT_VAL Split = "val"
	SPLIT_TEST Split = "test"
)

// All allowed values of Split enum
var AllowedSplitEnumValues = []Split{
	"train",
	"val",
	"test",
}

func (v *Split) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Split(value)
	for _, existing := range AllowedSplitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Split", value)
}

// NewSplitFromValue returns a pointer to a valid Split
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSplitFromValue(v string) (*Split, error) {
	ev := Split(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Split: valid values are %v", v, AllowedSplitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Split) IsValid() bool {
	for _, existing := range AllowedSplitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Split value
func (v Split) Ptr() *Split {
	return &v
}

type NullableSplit struct {
	value *Split
	isSet bool
}

func (v NullableSplit) Get() *Split {
	return v.value
}

func (v *NullableSplit) Set(val *Split) {
	v.value = val
	v.isSet = true
}

func (v NullableSplit) IsSet() bool {
	return v.isSet
}

func (v *NullableSplit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSplit(val *Split) *NullableSplit {
	return &NullableSplit{value: val, isSet: true}
}

func (v NullableSplit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSplit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

