/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"fmt"
)

// OptimizerStrategy Pluggable optimizer strategies for the recursive self-improvement loop.  Each variant names a concrete prompt/agent optimizer family called for by ARCHITECTURE §20.10 #7.6 (\"named prompt/agent optimizer strategies, gated by held-out statistics\") and REQUIREMENTS R18.6. The names mirror the reflective-proposal direction of §21.3 and the deferred population search of §21.6c.  **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy only *proposes* [`CandidateChange`]s; it never *accepts* one. Every candidate from every strategy MUST flow through the existing held-out **Test** gate plus the `beater-stats` confidence interval already implemented here (`run_deterministic_experiment` / `run_judge_experiment` / `run_agent_experiment` → [`compare_paired_scores`] → [`GateDecision`], §21.3) and the planned §21.4 anti-overfitting guardrail before it can be accepted. Proposal is not acceptance: the strategy emits candidates, the gate decides.
type OptimizerStrategy string

// List of OptimizerStrategy
const (
	OPTIMIZERSTRATEGY_LLM_REWRITE OptimizerStrategy = "llm_rewrite"
	OPTIMIZERSTRATEGY_FEW_SHOT_BAYESIAN OptimizerStrategy = "few_shot_bayesian"
	OPTIMIZERSTRATEGY_MIPRO OptimizerStrategy = "mipro"
	OPTIMIZERSTRATEGY_EVOLUTIONARY OptimizerStrategy = "evolutionary"
	OPTIMIZERSTRATEGY_GEPA OptimizerStrategy = "gepa"
	OPTIMIZERSTRATEGY_PARAM_SEARCH OptimizerStrategy = "param_search"
)

// All allowed values of OptimizerStrategy enum
var AllowedOptimizerStrategyEnumValues = []OptimizerStrategy{
	"llm_rewrite",
	"few_shot_bayesian",
	"mipro",
	"evolutionary",
	"gepa",
	"param_search",
}

func (v *OptimizerStrategy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OptimizerStrategy(value)
	for _, existing := range AllowedOptimizerStrategyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OptimizerStrategy", value)
}

// NewOptimizerStrategyFromValue returns a pointer to a valid OptimizerStrategy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOptimizerStrategyFromValue(v string) (*OptimizerStrategy, error) {
	ev := OptimizerStrategy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OptimizerStrategy: valid values are %v", v, AllowedOptimizerStrategyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OptimizerStrategy) IsValid() bool {
	for _, existing := range AllowedOptimizerStrategyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OptimizerStrategy value
func (v OptimizerStrategy) Ptr() *OptimizerStrategy {
	return &v
}

type NullableOptimizerStrategy struct {
	value *OptimizerStrategy
	isSet bool
}

func (v NullableOptimizerStrategy) Get() *OptimizerStrategy {
	return v.value
}

func (v *NullableOptimizerStrategy) Set(val *OptimizerStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableOptimizerStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableOptimizerStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptimizerStrategy(val *OptimizerStrategy) *NullableOptimizerStrategy {
	return &NullableOptimizerStrategy{value: val, isSet: true}
}

func (v NullableOptimizerStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptimizerStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

