/*
Beater API

Agent observability, evaluation, gating, and human-review APIs for Beater

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beaterclient

import (
	"encoding/json"
	"fmt"
)

// RollupWeighting Whether a roll-up estimate honestly accounts for tail-sampling bias (§1 #9, #146). A tail-sampled population is deliberately non-representative, so an unweighted mean is a biased estimator of the population it was drawn from.
type RollupWeighting string

// List of RollupWeighting
const (
	ROLLUPWEIGHTING_HORVITZ_THOMPSON RollupWeighting = "horvitz_thompson"
	ROLLUPWEIGHTING_BIASED_UNWEIGHTED RollupWeighting = "biased_unweighted"
)

// All allowed values of RollupWeighting enum
var AllowedRollupWeightingEnumValues = []RollupWeighting{
	"horvitz_thompson",
	"biased_unweighted",
}

func (v *RollupWeighting) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RollupWeighting(value)
	for _, existing := range AllowedRollupWeightingEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RollupWeighting", value)
}

// NewRollupWeightingFromValue returns a pointer to a valid RollupWeighting
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRollupWeightingFromValue(v string) (*RollupWeighting, error) {
	ev := RollupWeighting(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RollupWeighting: valid values are %v", v, AllowedRollupWeightingEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RollupWeighting) IsValid() bool {
	for _, existing := range AllowedRollupWeightingEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RollupWeighting value
func (v RollupWeighting) Ptr() *RollupWeighting {
	return &v
}

type NullableRollupWeighting struct {
	value *RollupWeighting
	isSet bool
}

func (v NullableRollupWeighting) Get() *RollupWeighting {
	return v.value
}

func (v *NullableRollupWeighting) Set(val *RollupWeighting) {
	v.value = val
	v.isSet = true
}

func (v NullableRollupWeighting) IsSet() bool {
	return v.isSet
}

func (v *NullableRollupWeighting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollupWeighting(val *RollupWeighting) *NullableRollupWeighting {
	return &NullableRollupWeighting{value: val, isSet: true}
}

func (v NullableRollupWeighting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollupWeighting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

