# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ChangeKind(str, Enum):
    """
    The policy-π (§6.1) lever a [`CandidateChange`] targets, mirroring the planned §21.1 `ChangeKind` taxonomy. Kept internal to this crate; intentionally not a `/v1` contract type.
    """

    """
    allowed enum values
    """
    SYSTEM_PROMPT = 'system_prompt'
    CUSTOMER_PROMPT = 'customer_prompt'
    CODE = 'code'
    TOOL_ADD = 'tool_add'
    TOOL_REMOVE = 'tool_remove'
    MEMORY_CONFIG = 'memory_config'
    MODEL_PARAMS = 'model_params'
    DATA_LABEL = 'data_label'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChangeKind from a JSON string"""
        return cls(json.loads(json_str))


