# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OptimizerStrategy(str, Enum):
    """
    Pluggable optimizer strategies for the recursive self-improvement loop.  Each variant names a concrete prompt/agent optimizer family called for by ARCHITECTURE §20.10 #7.6 (\"named prompt/agent optimizer strategies, gated by held-out statistics\") and REQUIREMENTS R18.6. The names mirror the reflective-proposal direction of §21.3 and the deferred population search of §21.6c.  **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy only *proposes* [`CandidateChange`]s; it never *accepts* one. Every candidate from every strategy MUST flow through the existing held-out **Test** gate plus the `beater-stats` confidence interval already implemented here (`run_deterministic_experiment` / `run_judge_experiment` / `run_agent_experiment` → [`compare_paired_scores`] → [`GateDecision`], §21.3) and the planned §21.4 anti-overfitting guardrail before it can be accepted. Proposal is not acceptance: the strategy emits candidates, the gate decides.
    """

    """
    allowed enum values
    """
    LLM_REWRITE = 'llm_rewrite'
    FEW_SHOT_BAYESIAN = 'few_shot_bayesian'
    MIPRO = 'mipro'
    EVOLUTIONARY = 'evolutionary'
    GEPA = 'gepa'
    PARAM_SEARCH = 'param_search'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OptimizerStrategy from a JSON string"""
        return cls(json.loads(json_str))


