# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RollupWeighting(str, Enum):
    """
    Whether a roll-up estimate honestly accounts for tail-sampling bias (§1 #9, #146). A tail-sampled population is deliberately non-representative, so an unweighted mean is a biased estimator of the population it was drawn from.
    """

    """
    allowed enum values
    """
    HORVITZ_THOMPSON = 'horvitz_thompson'
    BIASED_UNWEIGHTED = 'biased_unweighted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RollupWeighting from a JSON string"""
        return cls(json.loads(json_str))


