# coding: utf-8

"""
    Beater API

    Agent observability, evaluation, gating, and human-review APIs for Beater

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Split(str, Enum):
    """
    Which split of the optimization substrate a [`CaseScore`] belongs to.  The RSI optimizer searches candidates against `Train`/`Val` and decides acceptance only on the held-out `Test` split (§21.4). The split assignment is the *caller's* responsibility — it owns the dataset and its train/val/test partition — so [`run_optimization_round`] never reshuffles or peeks at the split substrate; it merely routes each [`CaseScore`] to the gate by its tag.
    """

    """
    allowed enum values
    """
    TRAIN = 'train'
    VAL = 'val'
    TEST = 'test'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Split from a JSON string"""
        return cls(json.loads(json_str))


