<?php
/**
 * ProviderSecretsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beater\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Beater\Client\ApiException;
use Beater\Client\Configuration;
use Beater\Client\HeaderSelector;
use Beater\Client\ObjectSerializer;

/**
 * ProviderSecretsApi Class Doc Comment
 *
 * @category Class
 * @package  Beater\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProviderSecretsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createProviderSecret' => [
            'application/json',
        ],
        'listProviderSecrets' => [
            'application/json',
        ],
        'revokeProviderSecret' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createProviderSecret
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  \Beater\Client\Model\CreateProviderSecretHttpRequest $create_provider_secret_http_request create_provider_secret_http_request (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProviderSecret'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Beater\Client\Model\ProviderSecretMetadata|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse
     */
    public function createProviderSecret($tenant_id, $project_id, $create_provider_secret_http_request, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['createProviderSecret'][0])
    {
        list($response) = $this->createProviderSecretWithHttpInfo($tenant_id, $project_id, $create_provider_secret_http_request, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);
        return $response;
    }

    /**
     * Operation createProviderSecretWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  \Beater\Client\Model\CreateProviderSecretHttpRequest $create_provider_secret_http_request (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProviderSecret'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Beater\Client\Model\ProviderSecretMetadata|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createProviderSecretWithHttpInfo($tenant_id, $project_id, $create_provider_secret_http_request, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['createProviderSecret'][0])
    {
        $request = $this->createProviderSecretRequest($tenant_id, $project_id, $create_provider_secret_http_request, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Beater\Client\Model\ProviderSecretMetadata' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ProviderSecretMetadata' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ProviderSecretMetadata', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Beater\Client\Model\ProviderSecretMetadata';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ProviderSecretMetadata',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createProviderSecretAsync
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  \Beater\Client\Model\CreateProviderSecretHttpRequest $create_provider_secret_http_request (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProviderSecret'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProviderSecretAsync($tenant_id, $project_id, $create_provider_secret_http_request, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['createProviderSecret'][0])
    {
        return $this->createProviderSecretAsyncWithHttpInfo($tenant_id, $project_id, $create_provider_secret_http_request, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createProviderSecretAsyncWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  \Beater\Client\Model\CreateProviderSecretHttpRequest $create_provider_secret_http_request (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProviderSecret'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProviderSecretAsyncWithHttpInfo($tenant_id, $project_id, $create_provider_secret_http_request, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['createProviderSecret'][0])
    {
        $returnType = '\Beater\Client\Model\ProviderSecretMetadata';
        $request = $this->createProviderSecretRequest($tenant_id, $project_id, $create_provider_secret_http_request, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createProviderSecret'
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  \Beater\Client\Model\CreateProviderSecretHttpRequest $create_provider_secret_http_request (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProviderSecret'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createProviderSecretRequest($tenant_id, $project_id, $create_provider_secret_http_request, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['createProviderSecret'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling createProviderSecret'
            );
        }

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling createProviderSecret'
            );
        }

        // verify the required parameter 'create_provider_secret_http_request' is set
        if ($create_provider_secret_http_request === null || (is_array($create_provider_secret_http_request) && count($create_provider_secret_http_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_provider_secret_http_request when calling createProviderSecret'
            );
        }






        $resourcePath = '/v1/provider-secrets/{tenant_id}/{project_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($x_beater_api_key !== null) {
            $headerParams['x-beater-api-key'] = ObjectSerializer::toHeaderValue($x_beater_api_key);
        }
        // header params
        if ($x_beater_project_id !== null) {
            $headerParams['x-beater-project-id'] = ObjectSerializer::toHeaderValue($x_beater_project_id);
        }
        // header params
        if ($x_beater_environment_id !== null) {
            $headerParams['x-beater-environment-id'] = ObjectSerializer::toHeaderValue($x_beater_environment_id);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant_id' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_provider_secret_http_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_provider_secret_http_request));
            } else {
                $httpBody = $create_provider_secret_http_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listProviderSecrets
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProviderSecrets'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Beater\Client\Model\ProviderSecretMetadata[]|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse
     */
    public function listProviderSecrets($tenant_id, $project_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listProviderSecrets'][0])
    {
        list($response) = $this->listProviderSecretsWithHttpInfo($tenant_id, $project_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);
        return $response;
    }

    /**
     * Operation listProviderSecretsWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProviderSecrets'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Beater\Client\Model\ProviderSecretMetadata[]|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listProviderSecretsWithHttpInfo($tenant_id, $project_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listProviderSecrets'][0])
    {
        $request = $this->listProviderSecretsRequest($tenant_id, $project_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Beater\Client\Model\ProviderSecretMetadata[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ProviderSecretMetadata[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ProviderSecretMetadata[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Beater\Client\Model\ProviderSecretMetadata[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ProviderSecretMetadata[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listProviderSecretsAsync
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProviderSecrets'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listProviderSecretsAsync($tenant_id, $project_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listProviderSecrets'][0])
    {
        return $this->listProviderSecretsAsyncWithHttpInfo($tenant_id, $project_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listProviderSecretsAsyncWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProviderSecrets'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listProviderSecretsAsyncWithHttpInfo($tenant_id, $project_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listProviderSecrets'][0])
    {
        $returnType = '\Beater\Client\Model\ProviderSecretMetadata[]';
        $request = $this->listProviderSecretsRequest($tenant_id, $project_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listProviderSecrets'
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listProviderSecrets'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listProviderSecretsRequest($tenant_id, $project_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['listProviderSecrets'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling listProviderSecrets'
            );
        }

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling listProviderSecrets'
            );
        }






        $resourcePath = '/v1/provider-secrets/{tenant_id}/{project_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($x_beater_api_key !== null) {
            $headerParams['x-beater-api-key'] = ObjectSerializer::toHeaderValue($x_beater_api_key);
        }
        // header params
        if ($x_beater_project_id !== null) {
            $headerParams['x-beater-project-id'] = ObjectSerializer::toHeaderValue($x_beater_project_id);
        }
        // header params
        if ($x_beater_environment_id !== null) {
            $headerParams['x-beater-environment-id'] = ObjectSerializer::toHeaderValue($x_beater_environment_id);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant_id' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation revokeProviderSecret
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string $provider_secret_id provider_secret_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeProviderSecret'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Beater\Client\Model\RevokedProviderSecret|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse
     */
    public function revokeProviderSecret($tenant_id, $project_id, $provider_secret_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['revokeProviderSecret'][0])
    {
        list($response) = $this->revokeProviderSecretWithHttpInfo($tenant_id, $project_id, $provider_secret_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);
        return $response;
    }

    /**
     * Operation revokeProviderSecretWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string $provider_secret_id provider_secret_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeProviderSecret'] to see the possible values for this operation
     *
     * @throws \Beater\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Beater\Client\Model\RevokedProviderSecret|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse|\Beater\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function revokeProviderSecretWithHttpInfo($tenant_id, $project_id, $provider_secret_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['revokeProviderSecret'][0])
    {
        $request = $this->revokeProviderSecretRequest($tenant_id, $project_id, $provider_secret_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Beater\Client\Model\RevokedProviderSecret' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\RevokedProviderSecret' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\RevokedProviderSecret', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Beater\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Beater\Client\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Beater\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Beater\Client\Model\RevokedProviderSecret';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\RevokedProviderSecret',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Beater\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation revokeProviderSecretAsync
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string $provider_secret_id provider_secret_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeProviderSecret'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function revokeProviderSecretAsync($tenant_id, $project_id, $provider_secret_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['revokeProviderSecret'][0])
    {
        return $this->revokeProviderSecretAsyncWithHttpInfo($tenant_id, $project_id, $provider_secret_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation revokeProviderSecretAsyncWithHttpInfo
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string $provider_secret_id provider_secret_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeProviderSecret'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function revokeProviderSecretAsyncWithHttpInfo($tenant_id, $project_id, $provider_secret_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['revokeProviderSecret'][0])
    {
        $returnType = '\Beater\Client\Model\RevokedProviderSecret';
        $request = $this->revokeProviderSecretRequest($tenant_id, $project_id, $provider_secret_id, $authorization, $x_beater_api_key, $x_beater_project_id, $x_beater_environment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'revokeProviderSecret'
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $project_id project_id (required)
     * @param  string $provider_secret_id provider_secret_id (required)
     * @param  string|null $authorization Bearer API token for strict auth (optional)
     * @param  string|null $x_beater_api_key API key alternative for strict auth (optional)
     * @param  string|null $x_beater_project_id Strict-auth project scope (optional)
     * @param  string|null $x_beater_environment_id Strict-auth environment scope (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeProviderSecret'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function revokeProviderSecretRequest($tenant_id, $project_id, $provider_secret_id, $authorization = null, $x_beater_api_key = null, $x_beater_project_id = null, $x_beater_environment_id = null, string $contentType = self::contentTypes['revokeProviderSecret'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling revokeProviderSecret'
            );
        }

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling revokeProviderSecret'
            );
        }

        // verify the required parameter 'provider_secret_id' is set
        if ($provider_secret_id === null || (is_array($provider_secret_id) && count($provider_secret_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $provider_secret_id when calling revokeProviderSecret'
            );
        }






        $resourcePath = '/v1/provider-secrets/{tenant_id}/{project_id}/{provider_secret_id}/revoke';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($x_beater_api_key !== null) {
            $headerParams['x-beater-api-key'] = ObjectSerializer::toHeaderValue($x_beater_api_key);
        }
        // header params
        if ($x_beater_project_id !== null) {
            $headerParams['x-beater-project-id'] = ObjectSerializer::toHeaderValue($x_beater_project_id);
        }
        // header params
        if ($x_beater_environment_id !== null) {
            $headerParams['x-beater-environment-id'] = ObjectSerializer::toHeaderValue($x_beater_environment_id);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenant_id' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($provider_secret_id !== null) {
            $resourcePath = str_replace(
                '{' . 'provider_secret_id' . '}',
                ObjectSerializer::toPathValue($provider_secret_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
