/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeKind : The policy-π (§6.1) lever a [`CandidateChange`] targets, mirroring the planned §21.1 `ChangeKind` taxonomy. Kept internal to this crate; intentionally not a `/v1` contract type.
/// The policy-π (§6.1) lever a [`CandidateChange`] targets, mirroring the planned §21.1 `ChangeKind` taxonomy. Kept internal to this crate; intentionally not a `/v1` contract type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeKind {
    #[serde(rename = "system_prompt")]
    SystemPrompt,
    #[serde(rename = "customer_prompt")]
    CustomerPrompt,
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "tool_add")]
    ToolAdd,
    #[serde(rename = "tool_remove")]
    ToolRemove,
    #[serde(rename = "memory_config")]
    MemoryConfig,
    #[serde(rename = "model_params")]
    ModelParams,
    #[serde(rename = "data_label")]
    DataLabel,

}

impl std::fmt::Display for ChangeKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SystemPrompt => write!(f, "system_prompt"),
            Self::CustomerPrompt => write!(f, "customer_prompt"),
            Self::Code => write!(f, "code"),
            Self::ToolAdd => write!(f, "tool_add"),
            Self::ToolRemove => write!(f, "tool_remove"),
            Self::MemoryConfig => write!(f, "memory_config"),
            Self::ModelParams => write!(f, "model_params"),
            Self::DataLabel => write!(f, "data_label"),
        }
    }
}

impl Default for ChangeKind {
    fn default() -> ChangeKind {
        Self::SystemPrompt
    }
}

