/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizerStrategy : Pluggable optimizer strategies for the recursive self-improvement loop.  Each variant names a concrete prompt/agent optimizer family called for by ARCHITECTURE §20.10 #7.6 (\"named prompt/agent optimizer strategies, gated by held-out statistics\") and REQUIREMENTS R18.6. The names mirror the reflective-proposal direction of §21.3 and the deferred population search of §21.6c.  **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy only *proposes* [`CandidateChange`]s; it never *accepts* one. Every candidate from every strategy MUST flow through the existing held-out **Test** gate plus the `beater-stats` confidence interval already implemented here (`run_deterministic_experiment` / `run_judge_experiment` / `run_agent_experiment` → [`compare_paired_scores`] → [`GateDecision`], §21.3) and the planned §21.4 anti-overfitting guardrail before it can be accepted. Proposal is not acceptance: the strategy emits candidates, the gate decides.
/// Pluggable optimizer strategies for the recursive self-improvement loop.  Each variant names a concrete prompt/agent optimizer family called for by ARCHITECTURE §20.10 #7.6 (\"named prompt/agent optimizer strategies, gated by held-out statistics\") and REQUIREMENTS R18.6. The names mirror the reflective-proposal direction of §21.3 and the deferred population search of §21.6c.  **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy only *proposes* [`CandidateChange`]s; it never *accepts* one. Every candidate from every strategy MUST flow through the existing held-out **Test** gate plus the `beater-stats` confidence interval already implemented here (`run_deterministic_experiment` / `run_judge_experiment` / `run_agent_experiment` → [`compare_paired_scores`] → [`GateDecision`], §21.3) and the planned §21.4 anti-overfitting guardrail before it can be accepted. Proposal is not acceptance: the strategy emits candidates, the gate decides.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OptimizerStrategy {
    #[serde(rename = "llm_rewrite")]
    LlmRewrite,
    #[serde(rename = "few_shot_bayesian")]
    FewShotBayesian,
    #[serde(rename = "mipro")]
    Mipro,
    #[serde(rename = "evolutionary")]
    Evolutionary,
    #[serde(rename = "gepa")]
    Gepa,
    #[serde(rename = "param_search")]
    ParamSearch,

}

impl std::fmt::Display for OptimizerStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LlmRewrite => write!(f, "llm_rewrite"),
            Self::FewShotBayesian => write!(f, "few_shot_bayesian"),
            Self::Mipro => write!(f, "mipro"),
            Self::Evolutionary => write!(f, "evolutionary"),
            Self::Gepa => write!(f, "gepa"),
            Self::ParamSearch => write!(f, "param_search"),
        }
    }
}

impl Default for OptimizerStrategy {
    fn default() -> OptimizerStrategy {
        Self::LlmRewrite
    }
}

