/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RollupEstimate : A population-mean roll-up paired with the honesty label saying whether it is inverse-probability weighted or a biased unweighted average (§1 #9). The label travels with the value so a caller can never silently render a tail-sampled average as if it were unbiased.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RollupEstimate {
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "weighting")]
    pub weighting: models::RollupWeighting,
}

impl RollupEstimate {
    /// A population-mean roll-up paired with the honesty label saying whether it is inverse-probability weighted or a biased unweighted average (§1 #9). The label travels with the value so a caller can never silently render a tail-sampled average as if it were unbiased.
    pub fn new(value: f64, weighting: models::RollupWeighting) -> RollupEstimate {
        RollupEstimate {
            value,
            weighting,
        }
    }
}

