/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RollupWeighting : Whether a roll-up estimate honestly accounts for tail-sampling bias (§1 #9, #146). A tail-sampled population is deliberately non-representative, so an unweighted mean is a biased estimator of the population it was drawn from.
/// Whether a roll-up estimate honestly accounts for tail-sampling bias (§1 #9, #146). A tail-sampled population is deliberately non-representative, so an unweighted mean is a biased estimator of the population it was drawn from.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RollupWeighting {
    #[serde(rename = "horvitz_thompson")]
    HorvitzThompson,
    #[serde(rename = "biased_unweighted")]
    BiasedUnweighted,

}

impl std::fmt::Display for RollupWeighting {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HorvitzThompson => write!(f, "horvitz_thompson"),
            Self::BiasedUnweighted => write!(f, "biased_unweighted"),
        }
    }
}

impl Default for RollupWeighting {
    fn default() -> RollupWeighting {
        Self::HorvitzThompson
    }
}

