/*
 * Beater API
 *
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Split : Which split of the optimization substrate a [`CaseScore`] belongs to.  The RSI optimizer searches candidates against `Train`/`Val` and decides acceptance only on the held-out `Test` split (§21.4). The split assignment is the *caller's* responsibility — it owns the dataset and its train/val/test partition — so [`run_optimization_round`] never reshuffles or peeks at the split substrate; it merely routes each [`CaseScore`] to the gate by its tag.
/// Which split of the optimization substrate a [`CaseScore`] belongs to.  The RSI optimizer searches candidates against `Train`/`Val` and decides acceptance only on the held-out `Test` split (§21.4). The split assignment is the *caller's* responsibility — it owns the dataset and its train/val/test partition — so [`run_optimization_round`] never reshuffles or peeks at the split substrate; it merely routes each [`CaseScore`] to the gate by its tag.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Split {
    #[serde(rename = "train")]
    Train,
    #[serde(rename = "val")]
    Val,
    #[serde(rename = "test")]
    Test,

}

impl std::fmt::Display for Split {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Train => write!(f, "train"),
            Self::Val => write!(f, "val"),
            Self::Test => write!(f, "test"),
        }
    }
}

impl Default for Split {
    fn default() -> Split {
        Self::Train
    }
}

