/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/ChangeKind.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

ChangeKind::eChangeKind toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("system_prompt")))
        return ChangeKind::eChangeKind::ChangeKind_SYSTEM_PROMPT;
    if (val == utility::conversions::to_string_t(U("customer_prompt")))
        return ChangeKind::eChangeKind::ChangeKind_CUSTOMER_PROMPT;
    if (val == utility::conversions::to_string_t(U("code")))
        return ChangeKind::eChangeKind::ChangeKind_CODE;
    if (val == utility::conversions::to_string_t(U("tool_add")))
        return ChangeKind::eChangeKind::ChangeKind_TOOL_ADD;
    if (val == utility::conversions::to_string_t(U("tool_remove")))
        return ChangeKind::eChangeKind::ChangeKind_TOOL_REMOVE;
    if (val == utility::conversions::to_string_t(U("memory_config")))
        return ChangeKind::eChangeKind::ChangeKind_MEMORY_CONFIG;
    if (val == utility::conversions::to_string_t(U("model_params")))
        return ChangeKind::eChangeKind::ChangeKind_MODEL_PARAMS;
    if (val == utility::conversions::to_string_t(U("data_label")))
        return ChangeKind::eChangeKind::ChangeKind_DATA_LABEL;
    return {};
}

EnumUnderlyingType fromEnum(ChangeKind::eChangeKind e)
{
    switch (e)
    {
    case ChangeKind::eChangeKind::ChangeKind_SYSTEM_PROMPT:
        return U("system_prompt");
    case ChangeKind::eChangeKind::ChangeKind_CUSTOMER_PROMPT:
        return U("customer_prompt");
    case ChangeKind::eChangeKind::ChangeKind_CODE:
        return U("code");
    case ChangeKind::eChangeKind::ChangeKind_TOOL_ADD:
        return U("tool_add");
    case ChangeKind::eChangeKind::ChangeKind_TOOL_REMOVE:
        return U("tool_remove");
    case ChangeKind::eChangeKind::ChangeKind_MEMORY_CONFIG:
        return U("memory_config");
    case ChangeKind::eChangeKind::ChangeKind_MODEL_PARAMS:
        return U("model_params");
    case ChangeKind::eChangeKind::ChangeKind_DATA_LABEL:
        return U("data_label");
    default:
        break;
    }
    return {};
}
}

ChangeKind::ChangeKind()
{
}

ChangeKind::~ChangeKind()
{
}

void ChangeKind::validate()
{
    // TODO: implement validation
}

web::json::value ChangeKind::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool ChangeKind::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void ChangeKind::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool ChangeKind::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

ChangeKind::eChangeKind ChangeKind::getValue() const
{
   return m_value;
}

void ChangeKind::setValue(ChangeKind::eChangeKind const value)
{
   m_value = value;
}

}
}
}
}


