/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/OptimizerStrategy.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

OptimizerStrategy::eOptimizerStrategy toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("llm_rewrite")))
        return OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_LLM_REWRITE;
    if (val == utility::conversions::to_string_t(U("few_shot_bayesian")))
        return OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_FEW_SHOT_BAYESIAN;
    if (val == utility::conversions::to_string_t(U("mipro")))
        return OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_MIPRO;
    if (val == utility::conversions::to_string_t(U("evolutionary")))
        return OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_EVOLUTIONARY;
    if (val == utility::conversions::to_string_t(U("gepa")))
        return OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_GEPA;
    if (val == utility::conversions::to_string_t(U("param_search")))
        return OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_PARAM_SEARCH;
    return {};
}

EnumUnderlyingType fromEnum(OptimizerStrategy::eOptimizerStrategy e)
{
    switch (e)
    {
    case OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_LLM_REWRITE:
        return U("llm_rewrite");
    case OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_FEW_SHOT_BAYESIAN:
        return U("few_shot_bayesian");
    case OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_MIPRO:
        return U("mipro");
    case OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_EVOLUTIONARY:
        return U("evolutionary");
    case OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_GEPA:
        return U("gepa");
    case OptimizerStrategy::eOptimizerStrategy::OptimizerStrategy_PARAM_SEARCH:
        return U("param_search");
    default:
        break;
    }
    return {};
}
}

OptimizerStrategy::OptimizerStrategy()
{
}

OptimizerStrategy::~OptimizerStrategy()
{
}

void OptimizerStrategy::validate()
{
    // TODO: implement validation
}

web::json::value OptimizerStrategy::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool OptimizerStrategy::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void OptimizerStrategy::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool OptimizerStrategy::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

OptimizerStrategy::eOptimizerStrategy OptimizerStrategy::getValue() const
{
   return m_value;
}

void OptimizerStrategy::setValue(OptimizerStrategy::eOptimizerStrategy const value)
{
   m_value = value;
}

}
}
}
}


