/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/RollupEstimate.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RollupEstimate::RollupEstimate()
{
    m_Value = 0.0;
    m_ValueIsSet = false;
    m_WeightingIsSet = false;
}

RollupEstimate::~RollupEstimate()
{
}

void RollupEstimate::validate()
{
    // TODO: implement validation
}

web::json::value RollupEstimate::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ValueIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_WeightingIsSet)
    {   
        
        val[utility::conversions::to_string_t(U("weighting"))] = ModelBase::toJson(m_Weighting);
    }

    return val;
}

bool RollupEstimate::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(U("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("value")));
        if(!fieldValue.is_null())
        {
            double refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("weighting"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("weighting")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<RollupWeighting> refVal_setWeighting;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeighting);
            setWeighting(refVal_setWeighting);
            
        }
    }
    return ok;
}

void RollupEstimate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("value")), m_Value));
    }
    if(m_WeightingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("weighting")), m_Weighting));
    }
}

bool RollupEstimate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("value"))))
    {
        double refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("weighting"))))
    {
        std::shared_ptr<RollupWeighting> refVal_setWeighting;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("weighting"))), refVal_setWeighting );
        setWeighting(refVal_setWeighting);
    }
    return ok;
}


double RollupEstimate::getValue() const
{
    return m_Value;
}

void RollupEstimate::setValue(double value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool RollupEstimate::valueIsSet() const
{
    return m_ValueIsSet;
}

void RollupEstimate::unsetValue()
{
    m_ValueIsSet = false;
}
std::shared_ptr<RollupWeighting> RollupEstimate::getWeighting() const
{
    return m_Weighting;
}


void RollupEstimate::setWeighting(const std::shared_ptr<RollupWeighting>& value)
{
    m_Weighting = value;
    m_WeightingIsSet = true;
}

bool RollupEstimate::weightingIsSet() const
{
    return m_WeightingIsSet;
}

void RollupEstimate::unsetWeighting()
{
    m_WeightingIsSet = false;
}

}
}
}
}


