/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/RollupWeighting.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

RollupWeighting::eRollupWeighting toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("horvitz_thompson")))
        return RollupWeighting::eRollupWeighting::RollupWeighting_HORVITZ_THOMPSON;
    if (val == utility::conversions::to_string_t(U("biased_unweighted")))
        return RollupWeighting::eRollupWeighting::RollupWeighting_BIASED_UNWEIGHTED;
    return {};
}

EnumUnderlyingType fromEnum(RollupWeighting::eRollupWeighting e)
{
    switch (e)
    {
    case RollupWeighting::eRollupWeighting::RollupWeighting_HORVITZ_THOMPSON:
        return U("horvitz_thompson");
    case RollupWeighting::eRollupWeighting::RollupWeighting_BIASED_UNWEIGHTED:
        return U("biased_unweighted");
    default:
        break;
    }
    return {};
}
}

RollupWeighting::RollupWeighting()
{
}

RollupWeighting::~RollupWeighting()
{
}

void RollupWeighting::validate()
{
    // TODO: implement validation
}

web::json::value RollupWeighting::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool RollupWeighting::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void RollupWeighting::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool RollupWeighting::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

RollupWeighting::eRollupWeighting RollupWeighting::getValue() const
{
   return m_value;
}

void RollupWeighting::setValue(RollupWeighting::eRollupWeighting const value)
{
   m_value = value;
}

}
}
}
}


