/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "beater-client/model/Split.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

Split::eSplit toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("train")))
        return Split::eSplit::Split_TRAIN;
    if (val == utility::conversions::to_string_t(U("val")))
        return Split::eSplit::Split_VAL;
    if (val == utility::conversions::to_string_t(U("test")))
        return Split::eSplit::Split_TEST;
    return {};
}

EnumUnderlyingType fromEnum(Split::eSplit e)
{
    switch (e)
    {
    case Split::eSplit::Split_TRAIN:
        return U("train");
    case Split::eSplit::Split_VAL:
        return U("val");
    case Split::eSplit::Split_TEST:
        return U("test");
    default:
        break;
    }
    return {};
}
}

Split::Split()
{
}

Split::~Split()
{
}

void Split::validate()
{
    // TODO: implement validation
}

web::json::value Split::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Split::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Split::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Split::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Split::eSplit Split::getValue() const
{
   return m_value;
}

void Split::setValue(Split::eSplit const value)
{
   m_value = value;
}

}
}
}
}


