/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The policy-π (§6.1) lever a [&#x60;CandidateChange&#x60;] targets, mirroring the planned §21.1 &#x60;ChangeKind&#x60; taxonomy. Kept internal to this crate; intentionally not a &#x60;/v1&#x60; contract type.
 */
public enum ChangeKind {
  
  SYSTEM_PROMPT("system_prompt"),
  
  CUSTOMER_PROMPT("customer_prompt"),
  
  CODE("code"),
  
  TOOL_ADD("tool_add"),
  
  TOOL_REMOVE("tool_remove"),
  
  MEMORY_CONFIG("memory_config"),
  
  MODEL_PARAMS("model_params"),
  
  DATA_LABEL("data_label");

  private String value;

  ChangeKind(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ChangeKind fromValue(String value) {
    for (ChangeKind b : ChangeKind.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

