/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Pluggable optimizer strategies for the recursive self-improvement loop.  Each variant names a concrete prompt/agent optimizer family called for by ARCHITECTURE §20.10 #7.6 (\&quot;named prompt/agent optimizer strategies, gated by held-out statistics\&quot;) and REQUIREMENTS R18.6. The names mirror the reflective-proposal direction of §21.3 and the deferred population search of §21.6c.  **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy only *proposes* [&#x60;CandidateChange&#x60;]s; it never *accepts* one. Every candidate from every strategy MUST flow through the existing held-out **Test** gate plus the &#x60;beater-stats&#x60; confidence interval already implemented here (&#x60;run_deterministic_experiment&#x60; / &#x60;run_judge_experiment&#x60; / &#x60;run_agent_experiment&#x60; → [&#x60;compare_paired_scores&#x60;] → [&#x60;GateDecision&#x60;], §21.3) and the planned §21.4 anti-overfitting guardrail before it can be accepted. Proposal is not acceptance: the strategy emits candidates, the gate decides.
 */
public enum OptimizerStrategy {
  
  LLM_REWRITE("llm_rewrite"),
  
  FEW_SHOT_BAYESIAN("few_shot_bayesian"),
  
  MIPRO("mipro"),
  
  EVOLUTIONARY("evolutionary"),
  
  GEPA("gepa"),
  
  PARAM_SEARCH("param_search");

  private String value;

  OptimizerStrategy(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OptimizerStrategy fromValue(String value) {
    for (OptimizerStrategy b : OptimizerStrategy.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

