/*
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.beater.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Which split of the optimization substrate a [&#x60;CaseScore&#x60;] belongs to.  The RSI optimizer searches candidates against &#x60;Train&#x60;/&#x60;Val&#x60; and decides acceptance only on the held-out &#x60;Test&#x60; split (§21.4). The split assignment is the *caller&#39;s* responsibility — it owns the dataset and its train/val/test partition — so [&#x60;run_optimization_round&#x60;] never reshuffles or peeks at the split substrate; it merely routes each [&#x60;CaseScore&#x60;] to the gate by its tag.
 */
public enum Split {
  
  TRAIN("train"),
  
  VAL("val"),
  
  TEST("test");

  private String value;

  Split(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Split fromValue(String value) {
    for (Split b : Split.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

