/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ChangeKind.h
 *
 * The policy-π (§6.1) lever a [&#x60;CandidateChange&#x60;] targets, mirroring the planned §21.1 &#x60;ChangeKind&#x60; taxonomy. Kept internal to this crate; intentionally not a &#x60;/v1&#x60; contract type.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ChangeKind_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ChangeKind_H_


#include "beater-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  ChangeKind
    : public ModelBase
{
public:
    ChangeKind();
    virtual ~ChangeKind();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eChangeKind
    {
        ChangeKind_SYSTEM_PROMPT,
        ChangeKind_CUSTOMER_PROMPT,
        ChangeKind_CODE,
        ChangeKind_TOOL_ADD,
        ChangeKind_TOOL_REMOVE,
        ChangeKind_MEMORY_CONFIG,
        ChangeKind_MODEL_PARAMS,
        ChangeKind_DATA_LABEL,
    };

    eChangeKind getValue() const;
    void setValue(eChangeKind const value);

    protected:
        eChangeKind m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ChangeKind_H_ */
