/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GateCandidateChangeRequest.h
 *
 * The candidate change being gated.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GateCandidateChangeRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GateCandidateChangeRequest_H_

#include <stdexcept>

#include "beater-client/ModelBase.h"

#include "beater-client/model/OptimizerStrategy.h"
#include <cpprest/details/basic_types.h>
#include "beater-client/model/ChangeKind.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// The candidate change being gated.
/// </summary>
class  GateCandidateChangeRequest
    : public ModelBase
{
public:
    GateCandidateChangeRequest();
    virtual ~GateCandidateChangeRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GateCandidateChangeRequest members


    /// <summary>
    /// Human-readable description of the proposed change.
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    /// <summary>
    /// The policy lever this change touches (e.g. &#x60;system_prompt&#x60;, &#x60;model_params&#x60;).
    /// </summary>
    std::shared_ptr<ChangeKind> getKind() const;
    bool kindIsSet() const;
    void unsetKind();
    void setKind(const std::shared_ptr<ChangeKind>& value);

    /// <summary>
    /// Which optimizer strategy emitted the candidate (e.g. &#x60;llm_rewrite&#x60;).
    /// </summary>
    std::shared_ptr<OptimizerStrategy> getProposedBy() const;
    bool proposedByIsSet() const;
    void unsetProposed_by();
    void setProposedBy(const std::shared_ptr<OptimizerStrategy>& value);

    /// <summary>
    /// Why the proposer believes this change helps (carried for audit).
    /// </summary>
    utility::string_t getRationale() const;
    bool rationaleIsSet() const;
    void unsetRationale();
    void setRationale(const utility::string_t& value);

    /// <summary>
    /// The file / symbol / prompt the change targets.
    /// </summary>
    utility::string_t getTarget() const;
    bool targetIsSet() const;
    void unsetTarget();
    void setTarget(const utility::string_t& value);


protected:
    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    std::shared_ptr<ChangeKind> m_Kind;
    bool m_KindIsSet;

    std::shared_ptr<OptimizerStrategy> m_Proposed_by;
    bool m_Proposed_byIsSet;

    utility::string_t m_Rationale;
    bool m_RationaleIsSet;

    utility::string_t m_Target;
    bool m_TargetIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GateCandidateChangeRequest_H_ */
