/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OptimizerStrategy.h
 *
 * Pluggable optimizer strategies for the recursive self-improvement loop.  Each variant names a concrete prompt/agent optimizer family called for by ARCHITECTURE §20.10 #7.6 (\&quot;named prompt/agent optimizer strategies, gated by held-out statistics\&quot;) and REQUIREMENTS R18.6. The names mirror the reflective-proposal direction of §21.3 and the deferred population search of §21.6c.  **Gating invariant — the differentiator vs. un-gated optimizers.** A strategy only *proposes* [&#x60;CandidateChange&#x60;]s; it never *accepts* one. Every candidate from every strategy MUST flow through the existing held-out **Test** gate plus the &#x60;beater-stats&#x60; confidence interval already implemented here (&#x60;run_deterministic_experiment&#x60; / &#x60;run_judge_experiment&#x60; / &#x60;run_agent_experiment&#x60; → [&#x60;compare_paired_scores&#x60;] → [&#x60;GateDecision&#x60;], §21.3) and the planned §21.4 anti-overfitting guardrail before it can be accepted. Proposal is not acceptance: the strategy emits candidates, the gate decides.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OptimizerStrategy_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OptimizerStrategy_H_


#include "beater-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  OptimizerStrategy
    : public ModelBase
{
public:
    OptimizerStrategy();
    virtual ~OptimizerStrategy();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eOptimizerStrategy
    {
        OptimizerStrategy_LLM_REWRITE,
        OptimizerStrategy_FEW_SHOT_BAYESIAN,
        OptimizerStrategy_MIPRO,
        OptimizerStrategy_EVOLUTIONARY,
        OptimizerStrategy_GEPA,
        OptimizerStrategy_PARAM_SEARCH,
    };

    eOptimizerStrategy getValue() const;
    void setValue(eOptimizerStrategy const value);

    protected:
        eOptimizerStrategy m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OptimizerStrategy_H_ */
