/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RollupEstimate.h
 *
 * A population-mean roll-up paired with the honesty label saying whether it is inverse-probability weighted or a biased unweighted average (§1 #9). The label travels with the value so a caller can never silently render a tail-sampled average as if it were unbiased.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RollupEstimate_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RollupEstimate_H_

#include <stdexcept>

#include "beater-client/ModelBase.h"

#include "beater-client/model/RollupWeighting.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// A population-mean roll-up paired with the honesty label saying whether it is inverse-probability weighted or a biased unweighted average (§1 #9). The label travels with the value so a caller can never silently render a tail-sampled average as if it were unbiased.
/// </summary>
class  RollupEstimate
    : public ModelBase
{
public:
    RollupEstimate();
    virtual ~RollupEstimate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RollupEstimate members


    double getValue() const;
    bool valueIsSet() const;
    void unsetValue();
    void setValue(double value);

    std::shared_ptr<RollupWeighting> getWeighting() const;
    bool weightingIsSet() const;
    void unsetWeighting();
    void setWeighting(const std::shared_ptr<RollupWeighting>& value);


protected:
    double m_Value;
    bool m_ValueIsSet;

    std::shared_ptr<RollupWeighting> m_Weighting;
    bool m_WeightingIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RollupEstimate_H_ */
