/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RollupWeighting.h
 *
 * Whether a roll-up estimate honestly accounts for tail-sampling bias (§1 #9, #146). A tail-sampled population is deliberately non-representative, so an unweighted mean is a biased estimator of the population it was drawn from.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RollupWeighting_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RollupWeighting_H_


#include "beater-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  RollupWeighting
    : public ModelBase
{
public:
    RollupWeighting();
    virtual ~RollupWeighting();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eRollupWeighting
    {
        RollupWeighting_HORVITZ_THOMPSON,
        RollupWeighting_BIASED_UNWEIGHTED,
    };

    eRollupWeighting getValue() const;
    void setValue(eRollupWeighting const value);

    protected:
        eRollupWeighting m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RollupWeighting_H_ */
