/**
 * Beater API
 * Agent observability, evaluation, gating, and human-review APIs for Beater
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Split.h
 *
 * Which split of the optimization substrate a [&#x60;CaseScore&#x60;] belongs to.  The RSI optimizer searches candidates against &#x60;Train&#x60;/&#x60;Val&#x60; and decides acceptance only on the held-out &#x60;Test&#x60; split (§21.4). The split assignment is the *caller&#39;s* responsibility — it owns the dataset and its train/val/test partition — so [&#x60;run_optimization_round&#x60;] never reshuffles or peeks at the split substrate; it merely routes each [&#x60;CaseScore&#x60;] to the gate by its tag.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Split_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Split_H_


#include "beater-client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  Split
    : public ModelBase
{
public:
    Split();
    virtual ~Split();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eSplit
    {
        Split_TRAIN,
        Split_VAL,
        Split_TEST,
    };

    eSplit getValue() const;
    void setValue(eSplit const value);

    protected:
        eSplit m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Split_H_ */
